apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod-replace.yaml
- pod-delete.yaml
- pod-deleteFromPrimitiveList.yaml
- pod-setElementOrder.yaml
patchesStrategicMerge:
- pod-replace.patch.yaml
- pod-delete.patch.yaml
- pod-deleteFromPrimitiveList.patch.yaml
- pod-setElementOrder.patch.yaml