apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-setElementOrder
  $setElementOrder/finalizers:
    - b
    - c
    - a
spec:
  selector:
    matchLabels:
      run: pod
  replicas: 1
  template:
    metadata:
      labels:
        run: pod
    spec:
      containers:
      - name: pod
        image: nginx
        ports:
        - containerPort: 80
